name: Deploy Demo
on:
    push:
        branches:
            - main
            - staging
            - dev
        paths:
            - "apps/demo/**"
    pull_request:
        branches:
            - main
            - staging
            - dev
        paths:
            - "apps/demo/**"
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to deploy to"
                required: true
                default: "development"
                type: string
                options:
                    - production
                    - staging
                    - development
jobs:
    deploy:
        name: Build & Deploy to Cloudflare Workers
        runs-on: ubuntu-latest
        needs: build
        timeout-minutes: 60
        environment:
            name: "Cloudflare Workers CI/CD"
        env:
            ENVIRONMENT: |-
                ${{ 
                    github.event.inputs.environment ||
                    github.ref_name == 'main' && 'production' || 
                    github.ref_name == 'staging' && 'staging' ||
                    github.ref_name == 'dev' && 'development' ||
                    'invalid'
                }}
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ vars.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Build Vite Project
              run: pnpm build --filter=@vesta-cx/euterpe-demo -- --mode ${{ env.ENVIRONMENT }}

            - name: Deploy Worker
              id: wrangler
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  environment: ${{ env.ENVIRONMENT }}
                  workingDirectory: apps/demo
                  packageManager: pnpm

            - name: Log Cloudflare Worker deployment details
              run: "echo '# Deployment details\n\n[Preview deployment](${{ steps.wrangler.outputs.deployment-url }}) (<${{ steps.wrangler.outputs.deployment-url }}>)' >> $GITHUB_STEP_SUMMARY"
