name: Build & Deploy Euterpe Demo
on:
    push:
        branches:
            - main
            - staging
            - dev
        paths:
            - "apps/demo/**"
    pull_request:
        branches:
            - main
            - staging
            - dev
        paths:
            - "apps/demo/**"
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to deploy to"
                required: true
                default: "staging"
                type: string
                options:
                    - production
                    - staging
                    - development
jobs:
    build:
        name: Build Vite Project
        runs-on: ubuntu-latest
        needs: install
        env:
            ENVIRONMENT: |-
                ${{ 
                    github.event.inputs.environment ||
                    github.ref_name == 'main' && 'production' || 
                    github.ref_name == 'staging' && 'staging' ||
                    github.ref_name == 'dev' && 'development' ||
                    'invalid'
                }}
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Cache Build Output
              id: cache-build-output
              uses: actions/cache@v4
              with:
                  path: "apps/demo/dist"
                  # from git branch and commit hash
                  key: ${{ runner.os }}-vite-build-${{ github.ref_name }}-${{ github.sha }}

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ vars.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Build Vite Project
              run: pnpm build --filter=@vesta-cx/euterpe-demo -- --mode ${{ env.ENVIRONMENT }}

    deploy:
        name: Deploy to Cloudflare Workers
        runs-on: ubuntu-latest
        needs: build
        timeout-minutes: 60
        environment:
            name: "Cloudflare Workers CI/CD"
        env:
            ENVIRONMENT: |-
                ${{ 
                    github.event.inputs.environment ||
                    github.ref_name == 'main' && 'production' || 
                    github.ref_name == 'staging' && 'staging' ||
                    github.ref_name == 'dev' && 'development' ||
                    'invalid'
                }}
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Restore Build Output
              id: cache-build-output
              uses: actions/cache@v4
              with:
                  fail-on-cache-miss: true
                  path: "apps/demo"
                  key: ${{ runner.os }}-vite-build-${{ github.ref_name }}-${{ github.sha }}

            - name: Build & Deploy Worker
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  environment: ${{ env.ENVIRONMENT }}
                  packageManager: pnpm
